---
  - name: Check all port numbers are accessible from the TrustGate
    wait_for:
      host:        "{{ item.server }}"
      port:        "{{ item.port }}"
      state:       started
      delay:       0
      timeout:     1
    ignore_errors: yes
    loop:
       - { server: 'localhost',      port: '22' }
       - { server: '109.207.15.2',   port: '443' }
       - { server: '10.112.132.254', port: '80' }      
       - { server: '10.112.132.253', port: '80' }
       - { server: '172.20.3.12',    port: '7500' }
       - { server: '172.20.3.12',    port: '21' }
       - { server: '192.168.100.2',  port: '9443' }

  - name: Check all host are accesible from EBS
    wait_for:
      host:        "{{ item.server }}"
      port:        "{{ item.port }}"
      state:       started
      delay:       0
      timeout:     1
    ignore_errors: yes
    loop:
       - { server: '192.168.101.3',      port: '443' }  # TrustGate
       - { server: '192.168.101.2',      port: '443' }  # IDS
       - { server: '192.168.101.1',      port: '8080' } # HW1000
       - { server: '192.168.101.50',     port: '443' }  # SSPT
       - { server: '192.168.101.4',      port: '443' }  # SWITHC
       - { server: '192.168.101.34',     port: '4443' } # TL
    delegate_to: 127.0.0.1

  - name: Other checks
    ansible.builtin.shell: journalctl --since '5 minutes ago' -u tg_failover > /home/iit/tests/jr.txt

  - name: Other checks
    ansible.builtin.shell: docker exec -it services_rabbit_1 rabbitmqctl list_queues -p r502  > /home/iit/tests/docker.txt
